### ISSUE TITLE
SMAA and Chromatic Aberration are not working together

### ISSUE THREAD

**Issue by Russo-creation** [pmndrs/react-postprocessing#100]
Hi, I'm trying to use SMAA and ChromaticAberration together in EffectComposer but SMAA effect erase ChromaticAberration effect. 

I prepared example with mentioned two effects [https://codesandbox.io/s/react-postprocessing-dof-blob-forked-s5cin?file=/src/App.js](https://codesandbox.io/s/react-postprocessing-dof-blob-forked-s5cin?file=/src/App.js) 

Does anyone find workaround to successfully use together effects?

**Comment by Cherna** [comment]
Just found the same issue, can't use SMAA with ChromaticAberration, it throws:
`Error: Convolution effects cannot be merged (ChromaticAberrationEffect)`

And also if I use Glitch with SMAA OR ChromaticAberration it throws:
`Error: Effects that transform UVs are incompatible with convolution effects (GlitchEffect)`

**Comment by ThreshHNS** [comment]
Any updates on this issue?
