### ISSUE TITLE
Dynamically changing camera causes normals to be rendered followed by crash 

### ISSUE THREAD

**Issue by looeee** [pmndrs/react-postprocessing#107]
Originally posted at https://github.com/pmndrs/react-three-fiber/discussions/709#discussioncomment-1851690

Here's [a sandbox](https://codesandbox.io/s/r3f-camera-transition-with-effects-green-flash-zonbb) that will switch from ortho -> perspective on keypress. 

![2021-12-21 16_23_39-Sandbox - CodeSandbox](https://user-images.githubusercontent.com/5307958/146905056-3ee74de8-3a17-4e93-a93f-ac9107a36042.png)

When changing the camera like this using postprocessing there are two problems.

1. First, I thought there was a green frame flashing during the switch but after a few tries I managed to hit print screen at just the right moment and it's actually the normals being rendered for some reason - I think just for a single frame. 

![screen](https://user-images.githubusercontent.com/5307958/146904832-371a647f-1b47-4e0a-a528-8f8e1a119e22.png)

2. Next, if you switch between views a few times, it turns out that new WebGL contexts are being generated on each switch, and eventually you'll get a crash with these errors:

```
WARNING: Too many active WebGL contexts. Oldest context will be lost.

Uncaught TypeError: Cannot read properties of null (reading 'alpha')
    at EffectComposer.createBuffer (postprocessing.esm.js:3216)
    at new EffectComposer (postprocessing.esm.js:3138)
    
....

THREE.WebGLRenderer: Context Lost.
```

The crash is the same as #97.

**Comment by drcmda** [comment]
im going to fix it here: https://github.com/pmndrs/three-stdlib/blob/main/src/misc/WebGL.ts

**Comment by drcmda** [comment]
https://github.com/pmndrs/three-stdlib/commit/375e14084384fd6749d7219a7e71480f4e82fd98

**Comment by drcmda** [comment]
published a new minor 2.1.1 i can't reproduce your crash. the green thing - i don't know, looks like the normalpass leaks through. if i read this code right: https://github.com/pmndrs/react-postprocessing/blob/master/src/EffectComposer.tsx#L60-L63 then it unmounts the effects and the last one remaining is the normal, so maybe it glitches through. i guess we can fix that ... 🤔

**Comment by drcmda** [comment]
2.1.2 the glitch should also be taken care of.

**Comment by looeee** [comment]
Thank you. I'll test it in the morning.

**Comment by looeee** [comment]
Tested 2.1.2 and it's fixed!

Many thanks for for the speedy fix @drcmda 😁
