### ISSUE TITLE
SSAO seems to be inverted in my scene?

### ISSUE THREAD

**Issue by HybridFox** [pmndrs/react-postprocessing#115]
So i am kind of out of ideas for what this issue could be. But i am trying to simply implement SSAO in my three fiber scene. Using these settings (and with blendFunction NORMAL) I am able to get this showing:
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/7349146/155237063-ae3bb495-2656-4a60-83f1-d4c7df28cdc6.png">

But the SSAO seems to be inverted and incorrect, if anyone has an idea what i am doing wrong or with what settings i could fix this, i will be eternally grateful!

**Comment by drcmda** [comment]
yep, noticed it, too, postprocessing changed how ssao works it seems. i tried to look up what's going on but it seems to go through a major refactor. https://github.com/vanruesc/postprocessing/issues/279

**Comment by vanruesc** [comment]
Did this work with previous versions of `postprocessing`? Minor or patch versions are not supposed to introduce breaking changes; if they do then that's a bug. I'll investigate.

**Comment by drcmda** [comment]
hello @vanruesc yes, this came with an npm update

```diff
-    "postprocessing": "^6.23.3",
+    "postprocessing": "^6.24.0",
```

**Comment by vanruesc** [comment]
Is there any existing SSAO sandbox I could play around with?

**Comment by mikelyndon** [comment]
I ran into the same thing yesterday. Here's a broken version.
https://codesandbox.io/s/postprocessing-ssao-forked-xs05e0?file=/src/index.js
And an older working version
https://codesandbox.io/s/postprocessing-ssao-forked-ldgp2c

**Comment by vanruesc** [comment]
I tracked down the issue to this line: https://github.com/pmndrs/react-postprocessing/blob/e9bfdefa16adaaf8c221c3152b6e37924f0b124a/src/EffectComposer.tsx#L79 which was changed in 97cd9b65. The `NormalPass` never gets reanabled and thus never runs.

**Comment by drcmda** [comment]
oh may, what a typo :-S that fixed it! thanks a bunch @vanruesc

**Comment by HybridFox** [comment]
Indeed, v2.1.5 fixes it! Thank you so much for the quick action!

**Comment by PlopTheReal** [comment]
I'm on @react-three/postprocessing 2.1.6 + postprocessing 6.25.0 it seems I have this problem.

**Comment by PlopTheReal** [comment]
I've updated all the libs to the latest, it's ok!
