### ISSUE TITLE
Outline not showing

### ISSUE THREAD

**Issue by eriksachse** [pmndrs/react-postprocessing#116]
Hello,
I'm trying to get outlines on my object. Didn't work, every other Effect works. Here is an example, notice the Outline makes the scene brighter.

https://codesandbox.io/s/basic-demo-forked-r4lmsk?file=/src/App.js

**Comment by drcmda** [comment]
it seems to work: https://codesandbox.io/s/outlines-2rztl7 multisampling has to be 0 i think, this is a pp thing
