### ISSUE TITLE
Next.js ESM import issue

### ISSUE THREAD

**Issue by luksari** [pmndrs/react-postprocessing#120]
Hey there 👋🏼 
It seems that on versions `"@react-three/postprocessing": "^2.2.4"` in project using `"next": "12.1.0"` , there is an issue connected with importing `lodash-es/without`.

When importing any part of `@react-three/postprocessing` e.g `import { EffectComposer } from '@react-three/postprocessing'` on Next.js page, below issue happens.

```
error - Error [ERR_REQUIRE_ESM]: require() of ES Module /my-path/node_modules/lodash-es/without.js from /my-path/node_modules/@react-three/postprocessing/dist/index.cjs.js not supported.
Instead change the require of without.js in /my-path/node_modules/@react-three/postprocessing/dist/index.cjs.js to a dynamic import() which is available in all CommonJS modules.
```

I have tried transpiling dependency with `next-transpile-modules` but it did not solve the issue. 
The only thing that I have found and it might be connected with this issue, is your `package.json` does not have `"type": "module"` defined, but I am not sure if it does not break any other functionality if you add it.
Related issue on Stackoverflow: https://stackoverflow.com/a/65978156

Thanks for taking a look at this :) I hope that it will help you to solve this issue somehow.
Have a great day to the person that will take a look at this 😄

**Comment by CodyJasonBennett** [comment]
The problem here is that Selection uses an ESM-only dependency (which `type="module"` enables, not good).

I was able to remove it in #121, so things are as they were before. Will ship a patch in a moment.
