### ISSUE TITLE
`require() ... not supported` Error With Next.js

### ISSUE THREAD

**Issue by fweth** [pmndrs/react-postprocessing#122]
Hi, my coworker is using Next.js with Node v17.4.0 and encounters the following error when importing this package:

`Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/lukas/Desktop/live/fmb/node_modules/lodash-es/without.js from /Users/lukas/Desktop/live/fmb/node_modules/@react-three/postprocessing/dist/index.cjs.js not supported.
Instead change the require of without.js in /Users/lukas/Desktop/live/fmb/node_modules/@react-three/postprocessing/dist/index.cjs.js to a dynamic import() which is available in all CommonJS modules.`

I'm using Node v17.7.1 and also encountered this error before, but could resolve it with `npm update` (yet the project was created just last week, so either there is some coincidence, or a very recent update fixed it for me).

Any ideas?

**Comment by CodyJasonBennett** [comment]
This was fixed in 2.2.5 #121.
