### ISSUE TITLE
Depth of field: Can I keep the camera target in focus? [sandbox]

### ISSUE THREAD

**Issue by marcelpi** [pmndrs/react-postprocessing#131]
I'm trying to add a little blur to my scene and would want to keep the target point in focus, while the rest is affected by the blur.

Does anybody know how these focusDistance and focusLength parameters work? Both take values from 0 to 1, but I wasn't able to figure out what they mean.

For focusDistance is 0 the camera point and 1 infinity?

I've set up an example in this sandbox: https://codesandbox.io/s/dof-example-z2wnhn?file=/src/App.js
I'm trying to make the magenta ball in the middle stay in focus, while the other boxes get blurry.

Please help.

**Comment by chasedavis** [comment]
I haven't tried it but dof effect has `target` for referencing focus point from a vec3?

https://pmndrs.github.io/postprocessing/public/docs/class/src/effects/DepthOfFieldEffect.js~DepthOfFieldEffect.html

**Comment by marcelpi** [comment]
Awesome, thanks Chase. Much appreciated.
Seems like only ref.current.target = targetGeometry.current.position needs to be set, without targetPosition = [0, 0, 0].

Anyway, you just solved my problem.
Cheers.

**Comment by marcelpi** [comment]
> https://pmndrs.github.io/postprocessing/public/docs/class/src/effects/DepthOfFieldEffect.js~DepthOfFieldEffect.html

Pardon me asking, but where did you find this documentation? Are there any others aside from postprocessing?
First time I see it, besides the official Three and [React PostProcessing docs](https://docs.pmnd.rs/react-postprocessing/introduction) which do not mention target.

**Comment by chasedavis** [comment]
It's linked to in the [postprocessing readme](https://github.com/pmndrs/postprocessing) as Documentation.

I think the docs recently moved URLs which is maybe why it's a bit tougher to find at the moment
