### ISSUE TITLE
Cannot resolve /jsm/capabilities/WebGL

### ISSUE THREAD

**Issue by federicovezzoli** [pmndrs/react-postprocessing#138]
Hi, 
using the latest version of three.js (0.142.0) I get an error when importing the lib:

`Error: Cannot find module '/xxxx/node_modules/three/examples/jsm/capabilities/WebGL'`

I've tracked the error back to `screen-space-reflections` and they updated the code in the latest release (2.0.4), but I think you have to update the package dependencies as well.

thanks!

**Comment by alexzaganelli** [comment]
I have the same issue too, in Next.js

**Comment by desmon91** [comment]
I believe this problem is still flagged as a bug here https://github.com/pmndrs/react-postprocessing/issues/72
and because of this specific issue, I still use the version "@react-three/postprocessing": "^2.0.1" on my nextjs

**Comment by robksawyer** [comment]
Thanks for opening this up. I am having the same issue in the latest version of NextJS.

**Comment by Jirayu-ninl** [comment]
I have the same issue too. It was solved in 2.5.0 about 2 hours ago.

**Comment by federicovezzoli** [comment]
solved in 2.5.0 for me too
