### ISSUE TITLE
RFC: react-postprocessing storybook

### ISSUE THREAD

**Issue by gsimone** [pmndrs/react-postprocessing#14]
It's been a success for drei ( every new contributer uses the storybook to create the components or at least creates a story when contributing ) and it's easy to keep it updated. 
Having to updated 20 sandboxes may be counterproductive, especially if only 1 person can do it, while the storybook uses the latest dependencies and imports the component from the source.

**Comment by talentlessguy** [comment]
or, we could setup a Docz site

but tbf doesn't matter much - storybook is good as well

(mb also Next.js + MDX as an option? (probably overkill))

**Comment by talentlessguy** [comment]
since there will be a website for centralized docs of all pmndrs libs this issue is no longer an issue

sooo closing
