### ISSUE TITLE
docs 404

### ISSUE THREAD

**Issue by JosephClay** [pmndrs/react-postprocessing#149]
https://docs.pmnd.rs/react-postprocessing redirects to https://github.com/pmndrs/react-three-postprocessing#readme displaying a 404

**Comment by JosephClay** [comment]
would love to help with this issue to get the docs back up

lemme know if there's anything i can do

**Comment by CodyJasonBennett** [comment]
Should be good now.

**Comment by JosephClay** [comment]
the redirect is valid now, but it's not pointing to the docs, it's pointing to the readme

**Comment by CodyJasonBennett** [comment]
Looks like it was removed and never migrated. I restored the docs from my fork in #153. Once that's merged it should update with changes made here.
