### ISSUE TITLE
Add Storybook (or alike)

### ISSUE THREAD

**Issue by servinlp** [pmndrs/react-postprocessing#150]
Continuing a discussion from https://github.com/pmndrs/react-postprocessing/issues/14

### What I want

A space to test out all effects with tools to tweak the settings. Think of [Leva](https://github.com/pmndrs/leva) or the controls panel from Storybook. As discussed in https://github.com/pmndrs/react-postprocessing/issues/14, there is documentation in both Markdown and the centralized docs but both feel lacking in controls and the demo's uses codesandbox so adding or updating becomes difficult.

### How I want it

A space where I as a user/contributor can easily add or fix a demo when needed (so no codesandbox for example). Personally I'm a big fan of how [Drei](https://drei.pmnd.rs/) does this with it's Storybook.

### Goal

Goal of this issue is to see if there is something others also want and what tool to maybe use.

**Comment by talentlessguy** [comment]
Latest rpp has Storybook so closing this
