### ISSUE TITLE
how to remove MAA from EffectComposer?

### ISSUE THREAD

**Issue by GrikFreak** [pmndrs/react-postprocessing#162]
Hi, 
is it possible to remove only the MAA antialiasing from EffectComposer? I can't find params to disable it.
i'm disabling EffectComposer while orbitcontrols are moving but it lags when i restart to move.
Only removing MAA should avoid this problem.
thanks

**Comment by CodyJasonBennett** [comment]
You can disable MSAA by setting `multisampling={0}`.
