### ISSUE TITLE
Memory leak on state update

### ISSUE THREAD

**Issue by m4cn4ir** [pmndrs/react-postprocessing#173]
Hi,

on state update, 2 more textures will be added per rerender. I prepared a sandbox for this:
https://codesandbox.io/s/react-pp-outlines-forked-g8tugo?file=/src/App.js

Also, for reference: https://discourse.threejs.org/t/properly-disposing-of-three-effectcomposer/8415/8

**Comment by lgharibashvili** [comment]
I have a similar issue when using DepthOfField. But adds 16 textures on each update.

**Comment by noelcserepy** [comment]
I also have this issue with Bloom and DepthOfField.

**Comment by KisonHe** [comment]
Same problem encountered. I need my website to talk to server, so the App will receive constant state updates. I noticed it seems that the Bloom in the EffectComposer is leaking GPU ram, but some other postprocessing like Outline is not leaking. Here is a code-sandbox https://codesandbox.io/s/gpu-ram-leak-example-5omr9d?file=/src/App.js 

Any idea on how to fix this for now or I have to stop using Bloom for a moment? :)
