### ISSUE TITLE
Make EffectComposer work with drei RenderTexture?

### ISSUE THREAD

**Issue by ethanchiu10** [pmndrs/react-postprocessing#186]
It would be great if the EffectComposer can render to a drei RenderTexture that is its parent, instead of rendering to screen.

**Comment by CodyJasonBennett** [comment]
You can access composer output as a texture from `composer.outputBuffer.texture` and set `composer.autoRenderToScreen = false` to take control.

**Comment by ethanchiu10** [comment]
@CodyJasonBennett can you show an example?
