### ISSUE TITLE
Outline -- while set visibleEdgeColor value , there is another object behind the object， outline color is transparent

### ISSUE THREAD

**Issue by KAI3546** [pmndrs/react-postprocessing#189]
when i set visibleEdgeColor value , there is another object behind the object， outline color is transparent, But I hope it's opaque

![截屏2023-04-27 18 09 56](https://user-images.githubusercontent.com/38448338/234831894-073ee4b2-0803-43e7-bb6e-67de18150982.png)

codepen link:
[https://codesandbox.io/s/selective-outlines-forked-kshjku?file=/src/App.js](https://codesandbox.io/s/selective-outlines-forked-kshjku?file=/src/App.js)

**Comment by btjacker** [comment]
import { BlendFunction } from 'postprocessing' 
and add blendFunction={BlendFunction.ALPHA} to your Outline component.

**Comment by KAI3546** [comment]
> import { BlendFunction } from 'postprocessing' and add blendFunction={BlendFunction.ALPHA} to your Outline component.

it's work, thanks
