### ISSUE TITLE
Jagged lines in Chrome (only with the Orthographic Camera)

### ISSUE THREAD

**Issue by fulopkovacs** [pmndrs/react-postprocessing#191]
# Description
I don't really know how to debug this, but when I have a scene with a GLTF model, a light source, and a Bloom effect, the edges of the model look very jagged in Chrome, if I use an Orthographic camera.

This phenomenon does not occur if:
- I don't use postprocessing
- use a Perspective camera
- switch to Firefox

Here are some screenshots:

## Orthographic Camera (Chrome ⬅️ ➡️ Firefox)
<img width="1511" alt="Screenshot 2023-04-29 at 16 12 14" src="https://user-images.githubusercontent.com/43729152/235307968-4d25e3b1-a2c6-48a9-a86b-b6fadd62c4bc.png">

## Perspective Camera (Chrome ⬅️ ➡️ Firefox)
<img width="1512" alt="Screenshot 2023-04-29 at 16 12 48" src="https://user-images.githubusercontent.com/43729152/235307974-26ff8cec-3618-4c99-9fca-fe8a29d4029c.png">

# Setup

I have a [🔗 Code Sandbox with a minimal reproducible example](https://codesandbox.io/p/github/fulopkovacs/jagged-lines-chrome-bloom-orthographic-camera/main?layout=%257B%2522activeFilepath%2522%253A%2522%252FREADME.md%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522fullScreenDevtools%2522%253Afalse%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522vertical%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522DEVTOOLS_PANELS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clh22a7ju00092e6new7xba19%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clh22a7ju00092e6new7xba19%2522%253A%257B%2522id%2522%253A%2522clh22a7ju00092e6new7xba19%2522%252C%2522activeTabId%2522%253A%2522clh22bww700co2e6nuyikgy3s%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clh22bvji006o2e6ncgpexbrs%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clh22bww700co2e6nuyikgy3s%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showSidebar%2522%253Atrue%252C%2522showDevtools%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%252C%2522editorPanelSize%2522%253A48.333333333333336%252C%2522devtoolsPanelSize%2522%253A35%257D).

| prop | value |
| --- | --- |
| Node version | `19.5.0` |
| OS | macOS Monterey, 12.2.1 |
| Chip | Apple M1 Pro |
| Memory | 32 GB |

Relevant Libraries:
```json
    "@react-three/drei": "^9.66.1",
    "@react-three/fiber": "^8.13.0",
    "@react-three/postprocessing": "^2.9.1",
    "@types/three": "^0.151.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "three": "^0.152.2"
```

# 🎦 Video

|  ⬅️ |  ➡️ |
| --- | --- |
| Chrome | Firefox | 
| ❌  | ✅  |

https://user-images.githubusercontent.com/43729152/235307617-2e099406-1410-4786-8c29-30d5688953ea.mp4

# 🧊 Minimal Reproducible Example

[🔗 Code Sandbox](https://codesandbox.io/p/github/fulopkovacs/jagged-lines-chrome-bloom-orthographic-camera/main?layout=%257B%2522activeFilepath%2522%253A%2522%252FREADME.md%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522fullScreenDevtools%2522%253Afalse%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522vertical%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522DEVTOOLS_PANELS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clh22a7ju00092e6new7xba19%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clh22a7ju00092e6new7xba19%2522%253A%257B%2522id%2522%253A%2522clh22a7ju00092e6new7xba19%2522%252C%2522activeTabId%2522%253A%2522clh22bww700co2e6nuyikgy3s%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clh22bvji006o2e6ncgpexbrs%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clh22bww700co2e6nuyikgy3s%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showSidebar%2522%253Atrue%252C%2522showDevtools%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%252C%2522editorPanelSize%2522%253A48.333333333333336%252C%2522devtoolsPanelSize%2522%253A35%257D)

I think I shared all the information that I have about this issue, but please let me know if there's anything missing from my report! ☺️

**Comment by ruslanvasylev** [comment]
This looks like an issue with polygon clipping.

Set your camera to:
<OrthographicCamera makeDefault position={[2, 3, 2]} zoom={400} **far={10}** />

**Comment by fulopkovacs** [comment]
Wooow, your suggestion did help! 🙌  

What's weird is that the clipping only occurs in Chrome + Safari, and not in Firefox... 🤷 

 Anyways, thank you for your help, I'll close this issue.
