### ISSUE TITLE
Effects wrapped with `wrapEffect` don't have access to any R3F and effect props

### ISSUE THREAD

**Issue by talentlessguy** [pmndrs/react-postprocessing#193]
Reproduction example: https://codesandbox.io/s/ancient-sky-ldkxwk?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/35937217/235353861-0581e986-7f30-4678-add7-19abad2f9ec9.png)

it should have `density` as a prop.

R3F props like `position`,`scale` don't exist either:

![image](https://user-images.githubusercontent.com/35937217/235353888-d1bc6cc7-293e-49c6-a4cb-24f8949e7dd3.png)

this happens only with effects wrapped in `wrapEffect`.

Most likely the cause is this piece of code:

https://github.com/pmndrs/react-postprocessing/blob/5fc540628930f882fca75ce07a1830de776f2ae8/src/util.tsx#L12-L19

A PR with fix is appreciated

**Comment by chasedavis** [comment]
I'm not sure if it's related, but using the opacity prop also breaks the effects ([example](https://codesandbox.io/s/opacity-rpp-issue-obx9ym?file=/src/App.tsx)) since 2.8.1 for me
