### ISSUE TITLE
Outline not showing for 2.9.0 and above

### ISSUE THREAD

**Issue by cosformula** [pmndrs/react-postprocessing#205]
## description
Outline not showing for 2.9.0 and above.
This demo working on 2.8.3 
<img width="1530" alt="image" src="https://github.com/pmndrs/react-postprocessing/assets/18232501/07c6ec39-4c82-495f-9b2b-50bc54e4b6fb">
And broken on 2.9.0 and above, including latest 2.11.3
<img width="1572" alt="image" src="https://github.com/pmndrs/react-postprocessing/assets/18232501/9065c48a-894d-402c-821f-2bbdfdeb7054">

## Step to reproduce
https://codesandbox.io/s/outline-not-showing-for-2-9-0-and-above-qkhn4l?file=/package.json

Change react-three/postprocessing version to 2.8.3, hover to the object and outline shows.

**Comment by AGPX** [comment]
I can confirm, I'm became crazy to figure out that was a bug!!!!!
