### ISSUE TITLE
react-native support?

### ISSUE THREAD

**Issue by bendgk** [pmndrs/react-postprocessing#223]
### Problem
I am trying to use the default example in my react native expo app but it doesn't seem to work.

### Steps to reproduce
1. `npm i @react-three/postprocessing `
2. setup the react-native app with the following:

```tsx
<Canvas>
  <ambientLight intensity={0.8} />
  <pointLight intensity={1} position={[0, 6, 0]} />
  <MyScene spawned={spawned} />
  <EffectComposer>
    <DepthOfField focusDistance={0} focalLength={0.02} bokehScale={2} height={480} />
    <Bloom luminanceThreshold={0} luminanceSmoothing={0.9} height={300} />
    <Noise opacity={0.02} />
    <Vignette eskil={false} offset={0.1} darkness={1.1} />
  </EffectComposer>
</Canvas>
```

3. observe the first error: `ReferenceError: Property 'atob' doesn't exist, js engine: hermes`
4. include a polyfill for atob in `postprocessing/dist/index.cjs` file

The polyfill:
```ts
var Buffer = require('buffer/').Buffer;
function atob(str) {
  return Buffer.from(str, 'base64').toString('binary');
}
function btoa(str) {
  return Buffer.from(str, 'binary').toString('base64');
}
```
 5. observe the second error: `Error: Exception in HostFunction: <unknown>, js engine: hermes`      

I'm not sure what to do about this error, and it seems to only happen with the `DepthOfField` effect so far when testing the following effects have **NOT** worked:
1. DepthOfField
2. AutoFocus

these effects I didn't test:
1. GodRays
2. Outline
3. SelectiveBloom

And SSAO made my phone (iPhone 12 pro) lag a bunch (not sure if I used it correctly.)
Every single other effect worked.

**Comment by CodyJasonBennett** [comment]
This looks to come from https://github.com/N8python/n8ao which we use for `<N8AO />` ([diff](https://github.com/search?q=repo%3AN8python%2Fn8ao%20atob&type=code))? Can you try that also?

If you're looking for a polyfill, there are various CPU-side ones like https://stackoverflow.com/a/42833475 which react-native should use internally recently.
