### ISSUE TITLE
No tone mapping exposure support

### ISSUE THREAD

**Issue by bhouston** [pmndrs/react-postprocessing#264]
From what I can tell there is no tone mapping support in this EffectComposer.  IT seems to ignore WebGLRenderer.toneMapping and WebGLRenderer.exposure.

**Comment by hezzy-cloudinary** [comment]
I experience the same problem. it kinda overrides `gl.toneMappingExposure` value

**Comment by davcri** [comment]
Tonemapping should be used as a postprocessing effect via https://github.com/pmndrs/react-postprocessing/blob/master/src/effects/ToneMapping.tsx

As for the exposure it should work unless there was some regression in the latest updates.

**Comment by bhouston** [comment]
It was just confusing.  toneMapping must be set via the ToneMapping EffectComposer Effect, but toneMappingExposure needs to be set on the WebGLRenderer.  I figured it out in the end.  It would be nicer to have exposure on ToneMapping effect.  Much less confusing.
