### ISSUE TITLE
disable multisampling when webgl2 isn't supported

### ISSUE THREAD

**Issue by drcmda** [pmndrs/react-postprocessing#28]
right now rpp crashes in safari.

**Comment by talentlessguy** [comment]
afaik three.js has `WebGL.isWebGL2Supported` – we could use it

will check again and PR

**Comment by drcmda** [comment]
i think we can even compare the renderer (gl = useThree()) against three.webgl1renderer or something like that

**Comment by austinmayer** [comment]
Great library, +1 on this issue.

**Comment by connorholyday** [comment]
This is what I'm doing to fix things at the moment:
```jsx
import { WEBGL } from 'three/examples/jsm/WebGL'

function Effects() {
  const multisampling = WEBGL.isWebGL2Available() === false ? 0 : 8

  render (<EffectComposer multisampling={multisampling}>{/* ... */}</EffectComposer>)
}
```

Could something like this be used to set the `multisampling` default to 0?

The content of `isWebGL2Available()` is [nice and small](https://github.com/mrdoob/three.js/blob/5e1417cb16b27868e63087a8eb0b3ac42d424fba/examples/jsm/WebGL.js#L20-L33)

**Comment by drcmda** [comment]
oh, yes, could you make a pr?

im guessing this function is new, so you can also do:

WEBGL?.isWebGL2Available() ? value : 0
