### ISSUE TITLE
Old N8AO dependency in package.json is causing Shader Error 0 when three.js > 0.166.0 is installed as well

### ISSUE THREAD

**Issue by ayan4m1** [pmndrs/react-postprocessing#291]
For context, see https://github.com/N8python/n8ao/issues/32

Basically, postprocessing depends explicitly on a [fairly old version of N8AO](https://github.com/pmndrs/react-postprocessing/blob/master/package.json#L51) , which is not compatible with Three.js starting from 0.166.0. This means that if you use the N8AO convenience component in postprocessing, you will get a Shader Error unless you hold three.js back.

I think there are multiple possible solutions here:

1. Kick the can and just bump n8ao to latest in package.json
2. Make n8ao a peerDependency with a semver range like "1.x" and then make the user install/upgrade it on their own
3. Document the bug and do nothing else

My preference would be for the second choice, but obviously open to discussion. Happy to open a PR if there is consensus.

Repro: https://github.com/ayan4m1/leela-memorial (then upgrade three.js to latest and run yarn install, npm start, go to "3D view" page and observe error)

**Comment by hallo-yurik** [comment]
I have the same error. On version three 0.168.0 "SSAO" doesn't work and after using "N8AO" I get this error

![image](https://github.com/user-attachments/assets/324b421f-e0a4-4888-a792-ea63e9233620)

**Comment by N8python** [comment]
This is because the N8AO they are using is very old :(. 1.9.2 is neccessary.

**Comment by CodyJasonBennett** [comment]
We're not able to use N8AO upstream since it pulls from `three/examples` and creates a dual package hazard for us. There is an additional issue of how/whether we update N8AO as it is not backwards compatible.

**Comment by ayan4m1** [comment]
Appreciate the fix!

**Comment by N8python** [comment]
Elaborate on what you mean by 'dual package hazard'? How would I alleviate this?

**Comment by N8python** [comment]
If N8AO was to be *entirely* self-contained, would this issue be resolved? And an update could be made?

**Comment by zrooda** [comment]
I'm getting a `Shader Error 0 - no default precision defined for variable 'vec2[4]'` on r170 with 2.16.3 of this lib, but only on certain devices (Pixel phones).

**Comment by ayan4m1** [comment]
@zrooda I'm not the author of the lib, but I'm unable to reproduce your issue, see [here](https://leelathebeagle.com/3d/) - this works in Chrome on my Pixel 4a. I have updated three to 0.171.0 and postprocessing to 2.16.3. If you run `npm ls n8ao` you should see version 1.9.3 - if not, that's your problem.
