### ISSUE TITLE
Error -  THREE.WebGLRenderer: WebGLMultisampleRenderTarget can only be used with WebGL2

### ISSUE THREAD

**Issue by jonportelli** [pmndrs/react-postprocessing#47]
I'm receiving the following console error in Firefox and Chrome but works fine in Safari. 
`THREE.WebGLRenderer: WebGLMultisampleRenderTarget can only be used with WebGL2`
It seems closely related to [this issue](https://github.com/pmndrs/react-postprocessing/issues/28). Any suggestions greatly appreciated.

**Comment by talentlessguy** [comment]
What version of FF and Chrome are you using?
