### ISSUE TITLE
ShaderPass Documentation / Help

### ISSUE THREAD

**Issue by austinmayer** [pmndrs/react-postprocessing#52]
Hi There!

I'm looking to render a shader material as a fullscreen effect via ShaderPass from postprocessing. Does the lib support anything like this at the moment? Here is my setup so far, but it results in `TypeError: effect.addEventListener is not a function`

```javascript
import React, { useMemo, forwardRef } from "react"
import * as THREE from "three"
import { EffectComposer } from "@react-three/postprocessing"
import { ShaderPass } from "postprocessing"

import HorizontalBlurShader from "../../shaders/HorizontalBlurShader"

const HorizontalBlur = forwardRef((options, ref) => {
  const blurShader = new THREE.RawShaderMaterial({
    uniforms: HorizontalBlurShader.uniforms,
    vertexShader: HorizontalBlurShader.vertexShader,
    fragmentShader: HorizontalBlurShader.fragmentShader
  })
  const effect = useMemo(() => new ShaderPass(blurShader, "tDiffuse"), [blurShader])
  return <primitive ref={ref} object={effect} dispose={null} />
})

function Effects() {
  return (
    <EffectComposer>      
      <HorizontalBlur />
    </EffectComposer>
  )
}
```

Any help would be much appreciated. Cheers!

EDIT: added Codesandbox for ref: https://codesandbox.io/s/r3f-postprocessing-shaderpass-rd-trp2u

**Comment by austinmayer** [comment]
Added a Codesandbox for ref: https://codesandbox.io/s/r3f-postprocessing-shaderpass-attempt-4w43o

**Comment by robksawyer** [comment]
@austinmayer the example is throwing an effect.initialize error. Any ideas?

**Comment by robksawyer** [comment]
@austinmayer I'm still kind of struggling with this myself, but using ShaderPass like the following seems to be working. I'm not sure how to get it working by using `postprocessing` and @react-three/postprocessing` ATM though. Been wrestling with this all day.

**Comment by austinmayer** [comment]
@robksawyer nice one. I'm in the same boat re: making custom passes work with a memoized imperative EffectComposer setup like you demoed above.

As far as I can tell, `postprocessing` does support custom passes with ShaderPass like so: https://github.com/vanruesc/postprocessing/wiki/Custom-Passes.

However, `@react-three/postprocessing` seems to only have support for more macro Effects at the moment. Writing custom Effects is possible in `postprocessing` as outlined here: https://github.com/vanruesc/postprocessing/wiki/Custom-Effects. I'm not quite at the point of re-writing my shaders to accommodate, but this is a pretty good guide to do it.

Would be interesting to see what, if any, the plans are for `@react-three/postprocessing` to handle custom full screen effects.

**Comment by talentlessguy** [comment]
I'm not an expert in this topic but all rpp's effects are imported from pp and each one of them seems to be extending [`Effect`](https://github.com/vanruesc/postprocessing/blob/master/src/effects/Effect.js#L14), maybe it's the key to solution.

Could you please try to construct an effect using `Effect` class from pp?

##### sorry if what I said doesn't help the issue

**Comment by austinmayer** [comment]
I'm trying to create a custom full screen effect, so yes, extending Effect and writing my own makes sense. Currently exploring the PostProcessing docs on custom Effects and necessary shader requirements to get them working. (https://github.com/vanruesc/postprocessing/wiki/Custom-Effects)

**Comment by austinmayer** [comment]
I ended up writing my own custom effects per the pp guide above. Steps I took:

- Rewrite my fragment shaders according to: https://github.com/vanruesc/postprocessing/wiki/Custom-Effects#fragment-shader
- Extend PostProcessing's `Effect`: https://codesandbox.io/s/r3f-postprocessing-customeffect-rd-4w43o?file=/effects/HorizontalBlur.js:210-214
- Create a custom effect like so: https://github.com/pmndrs/react-postprocessing/blob/master/api.md#custom-effects

I'm still not 100% on my shader re-writes, I don't feel like I'm using UVs correctly or perhaps the texture / inputBuffer bits are off. My effects work but there is a static part of the original scene that remains persistent and my custom effects aren't chaining effectively.

https://codesandbox.io/s/r3f-postprocessing-customeffect-rd-4w43o?file=/src/App.js

I realize this is now most likely outside of the scope of my original issue. I'm going to leave this open for now as a guide to get custom effects working until there is a more "official" call on whether fullscreen effects via ShaderPass have a home in `react-postprocessing`,

**Comment by austinmayer** [comment]
I got some good feedback on my shaders: https://github.com/vanruesc/postprocessing/issues/243

Updated sandbox for a custom BadTV Effect is here: https://codesandbox.io/s/r3f-postprocessing-customeffect-rd-4w43o?file=/src/App.js

**Comment by talentlessguy** [comment]
Is the issue still relevant or it can be considered as resolved?

**Comment by austinmayer** [comment]
Thanks for adding the example. Ok to close.

**Comment by RedRoosterMobile** [comment]
@austinmayer Did you resolve you UV issues with this "extends Effect"approach? I'm having the same issue with this one:

````// https://github.com/graywolf2/xr3ngine/blob/ca9685e35bc13d47bf0985eaca9ec34e324b17c0/packages/engine/src/renderer/postprocessing/FXAAEffect.ts
import React, { forwardRef, useMemo, useEffect } from 'react';
import { Uniform } from 'three';
import { Effect, BlendFunction } from 'postprocessing';
import glsl from 'babel-plugin-glsl/macro';
// no impl
// https://github.com/pmndrs/postprocessing/wiki/Custom-Effects
// with impl
// https://github.com/pmndrs/react-postprocessing/blob/master/api.md

// some custom shader code
const fragmentShader = glsl`
uniform float time;

void mainImage(const in vec4 inputColor, const in vec2 uv, out vec4 outputColor) {
    //vec2 vUv = uv.xy;
    float factor=3.0; // <-1.5
    vec2 uv1 = uv;
    float frequency = 6.0;
    float amplitude = 0.015 * factor;
    float x = uv1.y * frequency + time * .7;
    float y = uv1.x * frequency + time * .3;
    uv1.x += cos(x+y) * amplitude * cos(y);
    uv1.y += sin(x-y) * amplitude * cos(y);
    // https://github.com/aguilarmiqueas/car-game/blob/62872b759b9a28c75860347db311561b9a790bce/src/CustomPass.js
    // secrect sauce: inputBuffer.....man this took me hours to find
    vec4 rgba = texture2D(inputBuffer, uv1);
    outputColor= rgba;
    //outputColor = inputColor;
}`;
const vertexShader = glsl`
varying vec3 vNormal;
varying vec3 vPosition;
void mainSupport() {
  //vec4 modelViewPosition = modelViewMatrix * vec4(position, 1.);
  //gl_Position = projectionMatrix * modelViewPosition;
  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  //vNormal = (modelMatrix * vec4(normal, 0.0)).xyz;
  //vPosition = (modelMatrix * vec4(position, 1.0)).xyz;
}
`;

let _blendFunction;
let _time = 0;

// Effect implementation
class WaterEffectImpl extends Effect {
  constructor({} = {}) {
    super('WaterEffect', fragmentShader, {
      _blendFunction,
      uniforms: new Map([
        ['time', new Uniform(_time)]
      ]),
      vertexShader: vertexShader
    });
  }
  // (renderer, writeBuffer, readBuffer, deltaTime, maskActive) {
  update(renderer, inputBuffer, deltaTime) {
    _time += deltaTime;
    this.uniforms.set('time', { value: _time });
  }
}

// Effect component
export const WaterEffect = forwardRef(
  ({ blendFunction = BlendFunction.NORMAL }, ref) => {
    _blendFunction = blendFunction;
    const effect = useMemo(() => {
      return new WaterEffectImpl();
    }, []);
    return <primitive ref={ref} object={effect} />;
  }
);
```


it's somehow messing with all three dimensions and stuff will move around where it should not be. It's supposed to take whatever is gonna get rendered (with other FX) and apply that shader. Postprocessing..

like this:
https://www.shadertoy.com/view/cdlSW4


I do have another postprocessing attempt that works as expected, but it kills all previous effects..
see the mess below:

```
import * as THREE from 'three';
import glsl from 'babel-plugin-glsl/macro';
import React, { useRef, useMemo, useEffect } from 'react';
import { extend, useThree, useFrame, ShaderMaterial } from '@react-three/fiber';
// @ts-ignore
import {
  GlitchEffect,
  RenderPass,
  EffectComposer,
  EffectPass,
  NormalPass,
  ShaderPass,
} from 'postprocessing';
import { HalfFloatType, Vector2 } from 'three';

const uniforms = {
  tex: { value: null },
  time: { value: 0.0 },
  factor: { value: 0.5 },
  resolution: { value: new Vector2(64, 64) },
};

const Glitch = (glitchEffectProps) => {
  const { gl, scene, camera, size } = useThree();

  const composer = useMemo(() => {
    const effectComposer = new EffectComposer(gl, {
      frameBufferType: HalfFloatType,
    });
    effectComposer.addPass(new RenderPass(scene, camera));

    const normalPass = new NormalPass(scene, camera);

    effectComposer.addPass(normalPass);

    //const glitchEffect = new GlitchEffect(glitchEffectProps);

    const material = new THREE.ShaderMaterial({
      uniforms: {
        ...uniforms,
      },
      vertexShader:
        'varying vec2 vUv; void main() { vUv = uv; gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 ); }',
      fragmentShader: glsl`
      uniform float time;
      uniform float factor;
      uniform vec2 resolution;
      uniform sampler2D tex;
      varying vec2 vUv;
      void main() {
          vec2 uv1 = vUv;
          vec2 uv = gl_FragCoord.xy/resolution.xy;
          float frequency = 6.0;
          float amplitude = 0.015 * factor;
          float x = uv1.y * frequency + time * .7;
          float y = uv1.x * frequency + time * .3;
          uv1.x += cos(x+y) * amplitude * cos(y);
          uv1.y += sin(x-y) * amplitude * cos(y);
          vec4 rgba = texture2D(tex, uv1);
          gl_FragColor = rgba;
      }`,
    });
    material.map = true;
    const finalPass = new ShaderPass(material, 'tex');

    //
    //const waterEffect = new WaterEffect();

    //const glitchPass = new EffectPass(camera, glitchEffect);

    //glitchPass.renderToScreen = true;

    effectComposer.addPass(finalPass);

    return effectComposer;
  }, [camera, gl, scene, glitchEffectProps]);

  useEffect(() => composer.setSize(size.width, size.height), [composer, size]);
  return useFrame((_, delta) => {
    //console.log(_); // WebGlRenderer
    uniforms['time'].value += delta;
    composer.render(delta);
  }, 1);
};

export default Glitch;
```
