### ISSUE TITLE
Don't instantiate NormalPass if no Effects that use it are specified

### ISSUE THREAD

**Issue by unphased** [pmndrs/react-postprocessing#64]
So far, if SSAO is not being used, then it looks like there's no need to create a NormalPass to the composer. This should improve performance. If I understand this correctly, the NormalPass (unused by any effect other than SSAO) requires a re-render of the entire scene. This approach will likely halve framerate right off the bat, it is why MRT was invented. MRT can be done with WebGL2 but three.js does not support it. https://github.com/mrdoob/three.js/pull/16390 The good news is that it is possible that it could land soon.

**Comment by gsimone** [comment]
Could you open a PR to add a flag to the effectComposer component to turn normal on/off?

**Comment by gsimone** [comment]
If you need help, let's talk on the react-three--postprocessing channel on the pmndrs discord https://discord.gg/xSKQjggpeU

**Comment by unphased** [comment]
Sure, thanks for the invite! You think we should just add it as a boolean prop that defaults to the current behavior? I'll call it `disableNormalPass`?

**Comment by gsimone** [comment]
Yeah, that would be the safest bet and it would just be a minor release. We should keep in mind an eventual API change for a future major ✌️

**Comment by unphased** [comment]
Closing because #66 is merged, thanks.
