### ISSUE TITLE
Effects won't update after re-render

### ISSUE THREAD

**Issue by cihadturhan** [pmndrs/react-postprocessing#71]
After a re-render of the component, `Bloom` effect is broken (i.e. you cannot change its properties anymore)
I haven't checked with other components.
Please see repro
- You will see blinking bloom animation
- Click Toggle state button
- Blinking bloom animation is broken. Although `bloomRef.current.intensity` is changed, it has no effect on bloom

https://codesandbox.io/s/react-postprocessing-dof-blob-forked-8cu0k?file=/src/App.js

**Comment by noamgat** [comment]
I think its related to this:
https://github.com/pmndrs/react-postprocessing/issues/68

**Comment by cihadturhan** [comment]
@noamgat yes looks like so. Thanks.
