### ISSUE TITLE
v2.0 breaks animations until window is resized

### ISSUE THREAD

**Issue by neefrehman** [pmndrs/react-postprocessing#74]
i've just upgraded rpp to v2, but it's causing some havok with the renderloop. it looks as though no new frames are drawn, but when resizing the browser window you can see the scene update.

minimal repro: https://codesandbox.io/s/misty-rgb-ouo5x?file=/src/index.js

**Comment by randomValue** [comment]
The bug probably lies in this code section somehow when you hot reload it works just fine.

https://github.com/pmndrs/react-postprocessing/blob/99e7b9743a58b355295cbad6665567efaa11bd95/src/EffectComposer.tsx#L71-L81

**Comment by randomValue** [comment]
Threejs does not support multisampling as you can read [here](https://github.com/vanruesc/postprocessing/releases)
If you want EffectComposer to work set multisampling to 0 and add SMAA instead. Otherwise you could wait for three r128 or for now use the dev version.

**Comment by talentlessguy** [comment]
@randomValue yeah setting multisampling to 0 should resolve the issue

closing for now
