### ISSUE TITLE
[v2.0.2] WebGL error thrown and blocking

### ISSUE THREAD

**Issue by qpre** [pmndrs/react-postprocessing#78]
hello,

when using the library in its latest flavor (2.0.2) i get this message in chrome:

`[.WebGL-0x7fe1518be200]GL ERROR :GL_INVALID_OPERATION : glBlitFramebufferCHROMIUM: destination framebuffer is multisampled`

simply by having `<EffectComposer />` in .

Any idea how to circumvent this ?

**Comment by haywirez** [comment]
Had this issue a few days ago, use: `<EffectComposer multisampling={0} />` (correctly suggested by @talentlessguy)

**Comment by qpre** [comment]
@talentlessguy surely does not deserve their nickname, it works like a charm now.

Thanks a lot !

p.s: is there a process for adding it to the documentation ?

**Comment by talentlessguy** [comment]
@qpre if I'm correct there was a recent bug in THREE multisampler and that's why it suddenly broke

so I don't think it's worth mentioning it yet, the bug is already fixed but the patch release is not yet published

so I think we can close this?
