### ISSUE TITLE
Updating effects via `useFrame`

### ISSUE THREAD

**Issue by robksawyer** [pmndrs/react-postprocessing#8]
I've started a thread over in the react-three-fiber discussions (https://github.com/react-spring/react-three-fiber/discussions/595), but I'm wondering if you can add some insight. How should effects be updated after they're changed via `useFrame`? Sending these along to the EffectsComposer via state is not very efficient. And setting state inside of `useFrame` is really not a good idea.

**Comment by talentlessguy** [comment]
tbh I don't know, better ask @drcmda 

if u want to update ur effect conditionally, use `useLayoutEffect` hook like here:

```js
  useLayoutEffect(() => {
    if (depthTexture) {
      effect.setDepthTexture(depthTexture.texture, depthTexture.packing)
    }
  }, [depthTexture])
```

usage with `useFrame` - idk the best way to combine it w/ rpp

**Comment by drcmda** [comment]
i tried it out and it works, but you need to know postprocessing internals because the constructor parameters that you pass have are mapped to internals.

for instance this is how you fade Blooms luminianceThreshold:

```jsx
function Effects() {
  const ref = useRef()
  useFrame((state) => {
    if (ref.current) {
      ref.current.luminanceMaterial.threshold = 0.1 + (1 + Math.sin(state.clock.getElapsedTime() * 2)) / 3
    }
  }, [])
  return (
    <EffectComposer>
      <Bloom ref={ref} KernelSize={KernelSize.VERY_LARGE} height={400} opacity={2} />
      <SSAO />
    </EffectComposer>
  )
}
```

now that's unfortunate and mostly due to postprocessing not using getter/setters but contructor parameters. react-postprocessing could try to abstract this but it seems rather hacky, and pp could thrash that in any patch version.

**Comment by robksawyer** [comment]
Wow, that's a process for sure. But, nice work hacking this together! I really appreciate it.

**Comment by drcmda** [comment]
for this btw we could really need help, it would be easy to do:

```jsx
import { BloomEffect as BloomEffectImpl } from 'postprocessing'

class BloomEffect extends BloomEffectImpl {
  set luminanceThreshold(v) { this.luminanceMaterial.threshold = v }
  get luminanceThreshold() { return this.luminanceMaterial.threshold }
  ...
}
```

the react-pp effects would then instanciate that instead of the original. if you want @robksawyer PR's welcome 🙂

**Comment by talentlessguy** [comment]
I think it's safe to close this
