### ISSUE TITLE
Support for @react-three/fiber

### ISSUE THREAD

**Issue by AndrewJSchoen** [pmndrs/react-postprocessing#81]
It seems that this package is not compatible with the new naming convention of `react-three-fiber`, now `@react-three/fiber`. Using the `@react-three/fiber` package causes an error when the EffectComposer is added within a Canvas:

```
Uncaught R3F hooks can only be used within the Canvas component!
```

Presumably because it doesn't recognize the Canvas from `@react-three/fiber` as the same from `react-three-fiber`

**Comment by drcmda** [comment]
do you use @react-three/postprocessing ?

**Comment by AndrewJSchoen** [comment]
Ah, sorry, that is on me. I was going off the [examples](https://github.com/pmndrs/react-postprocessing/blob/master/api.md) which still use the old `react-postprocessing` naming.
