### ISSUE TITLE
Adding SSAO throws Normal Pass error

### ISSUE THREAD

**Issue by samuelcelko** [pmndrs/react-postprocessing#89]
Hey there, I was wondering if anyone knew how to add a normal pass to the EffectComposer -
as when I add `<SSAO/>` I get this error 

"_Please enable the NormalPass in the EffectComposer in order to use SSAO._"

see full code below

```
<EffectComposer autoClear={false}>
                <Noise opacity={0.02} />

                <SSAO
                    blendFunction={BlendFunction.MULTIPLY} 
                    samples={31}
                    radius={5}
                    intensity={30}
                />

                <SMAA />
 </EffectComposer>
```

Any help is appreciated. Thanks!

**Comment by samuelcelko** [comment]
Edit: seems to be a problem with version "@react-three/postprocessing": "^2.0.4-alpha.2",

lowering it to `2.0.3` solved the ssue for me

**Comment by drcmda** [comment]
i think its a bug, stable 2.04 has that as well.

**Comment by drcmda** [comment]
could you try 2.0.5? i reverted a commit that disables the normal pass.

**Comment by samuelcelko** [comment]
@drcmda can confirm it works as expected again on `2.0.5`

cheers
